### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by David-mca** [VitalikObject/OldBrawl#11]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\BLANK\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "F:\OldBrawl-main\server\main.py", line 60, in run
    crypter = Crypto()
              ^^^^^^^^
  File "F:\OldBrawl-main\server\Core\Crypto.py", line 30, in __init__
    self.client_pk = crypto_scalarmult_base(self.client_sk)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

**Comment by David-mca** [comment]
This only happens when a client connects to the server.

**Comment by David-mca** [comment]
Happens when connecting to the server from client

**Comment by David-mca** [comment]
Fixed!
If anyone else receive this error use Python 3.8.
